### ISSUE TITLE
Thumbnail width/height

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-plugin-albums#1]
These configurations are not used at all:  
![2016-03-10_17-56-59](https://cloud.githubusercontent.com/assets/7892851/13668846/932c0966-e6e9-11e5-80e0-42381d8d40e8.png)

**Comment by semchishinv** [comment]
It works fine. Maximum Thumb dimension is 150px by 150px. In this case 350px will work like 150px and no more
